[package]
name = "djikstra"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-beta.1"

[dev-dependencies]
rayon = "1.10.0"
plotters = { version = "0.3.7"}


#[profile.release]
#debug=1
#
#[profile.dev]
#debug=1
